version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./static/:/app/static/
    ports:
      - "1234:1234"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    env_file: 
      - ./2022-03-18-fastapi-beanie-one-page/.env
    ports:
      - "27017:27017"
    volumes:
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
